version: "3.9"

services:
  container_kicker:
    image: container_kicker
    restart: always
    expose: 
      - "41331"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - conf.env
    container_name: container_kicker
